version: 2.1
orbs:
  docker: circleci/docker@2.8.1
jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_LOGIN/$IMAGE_NAME
          tag: latest
      - docker/build:
          image: $DOCKER_LOGIN/$IMAGE_NAME
          tag: ${CIRCLE_SHA1}
      - docker/push:
          image: $DOCKER_LOGIN/$IMAGE_NAME
          tag: latest
      - docker/push:
          image: $DOCKER_LOGIN/$IMAGE_NAME
          tag: ${CIRCLE_SHA1}

workflows:
  commit:
    jobs:
      - build-and-push
