version: 2.1
orbs:
  docker: circleci/docker@2.8.1
jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_LOGIN/$IMAGE_NAME
      - docker/push:
          image: $DOCKER_LOGIN/$IMAGE_NAME
          tag: latest

workflows:
  commit:
    jobs:
      - build-and-push
