# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-and-push:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/base:current

    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18 # Or latest compatible version
      - docker/check: # Checks if docker is running
          docker-version: 20.10.18
      - run: # Login to Docker Hub using the access token
          name: Login to Docker Hub
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
      - docker/build:
          image: $DOCKER_USERNAME/$IMAGE_NAME
          tag: $CIRCLE_SHA1
          context: . # Build context (usually the project root)
      - docker/push:
          image: $DOCKER_USERNAME/$IMAGE_NAME
          tag: $CIRCLE_SHA1
      - docker/build: # Build with latest tag
          image: $DOCKER_USERNAME/$IMAGE_NAME
          tag: latest
          context: .
      - docker/push: # Push with latest tag
          image: $DOCKER_USERNAME/$IMAGE_NAME
          tag: latest

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-and-deploy:
    jobs:
      - build-and-push:
          filters:
            branches:
              only:
                - main
