version: 2.1
orbs:
  docker: circleci/docker@2.8.1
jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - run: # Login to Docker Hub using the access token
          name: Login to Docker Hub
          command: echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker/build: # Build and push with hash
          image: $DOCKER_USERNAME/$IMAGE_NAME
          tag: $CIRCLE_SHA1
      - docker/push:
          image: $DOCKER_USERNAME/$IMAGE_NAME
          tag: $CIRCLE_SHA1
      - docker/build: # Build and push with latest tag
          image: $DOCKER_USERNAME/$IMAGE_NAME
          tag: latest
      - docker/push:
          image: $DOCKER_USERNAME/$IMAGE_NAME
          tag: latest

workflows:
  commit:
    jobs:
      - build-and-push
